image:
  repository: leush91/habit-tracker
  tag: "039bf88"
app:
  replicas: 2
postgres:
  user: habituser
  db: habitdb
  passwordSecretName: postgres-secret
hpa:
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization: 50
