auth:
  adminUser: admin
  adminPassword: Leoadmin

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: auth.local
  path: /
  pathType: Prefix

postgresql:
  enabled: false
  primary:
    image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 16
externalDatabase:
  host: ""

keycloak:
  extraEnvVars:
    - name: KC_DB
      value: dev-mem    
