apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/keycloak
    repoURL: git@github.com:Leush91/habit-tracker-infra.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
