fluent-bit:
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush 1
          Log_Level info
          Parsers_File /fluent-bit/etc/parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 2020

    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*_app_*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 50MB
          Skip_Long_Lines On
          Refresh_Interval 5
          Inotify_Watcher false

    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude Off

      [FILTER]
          Name modify
          Match kube.*
          Add cluster_name kind-local
          Add source kubernetes

    outputs: |
      [OUTPUT]
          Name splunk
          Match kube.*
          Host splunk
          Port 8088
          TLS On
          TLS.Verify Off
          Splunk_Token e07d27be-425b-4357-bf69-ca7f17bcb7ef
          Splunk_Send_Raw Off
          event_source fluent-bit
          event_sourcetype habit-tracker-json
          event_index main
          compress gzip

  daemonSetVolumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers

  daemonSetVolumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true